#!/bin/bash

#This can run anytime we want to push the contents of <storage_dir> to mothership
LOCAL_STORAGE=/var/log/graphite/storage
TMP_TIME=/media/mothership/tmp_time
REM_STORAGE=/media/mothership/

DAT=`date +%N`
COUNT=0
#clear out old timestamps if there are any
rm -f ${TMP_TIME}/*

touch ${TMP_TIME}/${DAT}
while [ ! -e ${TMP_TIME}/${DAT} ] && [ ${COUNT} -lt 5 ]
do
  #we are not yet connected... wait a few and try again
  sleep 2
  touch ${TMP_TIME}/${DAT}
  echo "touch ${TMP_TIME}/${DAT} again"
  COUNT=$(($COUNT + 1))
done
if [ $COUNT -eq 5 ]
then
  echo "fail to connect?"
  exit 1
fi

#connected. Clean up and copy files.
rm -f ${TMP_TIME}/${DAT}

time rsync --exclude="log/" --exclude="*.pid" --delete -avz ${LOCAL_STORAGE} ${REM_STORAGE}
